### ISSUE TITLE
Update source?

### ISSUE THREAD

**Issue by noqqe** [bborbe/teamvault#1]
Hi

I've seen you updated the Image on DockerHub recently https://hub.docker.com/r/bborbe/teamvault/tags

But the source in this repo does not look like its matching. Can refresh this repo with the latest changes? 
Would be nice!

**Comment by bborbe** [comment]
The build instructions here are uptodate and use this sources: https://github.com/seibert-media/teamvault/tree/0.8.4

**Comment by noqqe** [comment]
Hi, thanks but thats not what i meant

The sources from the docker image that you built would be nice. Dockerfile, etc...  Currently the Image is ~14 days old and the repo here does not have an update since over a year.

**Comment by bborbe** [comment]
I have updated version and added some build instructions. Hope this solve this.

https://github.com/bborbe/teamvault#build-dockerimage

**Comment by noqqe** [comment]
Ah, alright that cleared things up. 
thanks.
